# Creacion de arreglos en Numpy

In [1]:
#Importar la libreria Numpy
import numpy as np

la forma de crear arreglo usando funcion array que toma como argumento de entrada una lista de Python

In [2]:
#creacion de arreglo 1D
a = np.array([1,2,3,4])
b = np.array([6.2,7.3,8.1,9.4])
print(a)
print(b)

[1 2 3 4]
[6.2 7.3 8.1 9.4]


In [3]:
#ambos arreglos son de tipo "ndarray"
print(type(a))
print(type(b))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [4]:
d = np.array([7,9.2,'hola',True])
print(d)
print(type(d))

['7' '9.2' 'hola' 'True']
<class 'numpy.ndarray'>


In [5]:
# Arreglo de 2D (matriz)
arr = np.array([[1,2,3,7],[4,5,6,8]])
print(arr)

[[1 2 3 7]
 [4 5 6 8]]


In [6]:
print(type(arr))

<class 'numpy.ndarray'>
