# Funciones `zeros()`, `ones()`, `full()`

permiten crear arreglos de cualquier tamaño con todos los valores iguales a cero (zeros), uno (ones), especifico (full)

In [18]:
import numpy as np

In [19]:
# arreglo de 3D con ceros
a = np.zeros((4, 2, 3))
print(a)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [20]:
print(f"Dimensiones del arreglo: {a.ndim}")
print(f"Forma del arreglo: {a.shape}")
print(f"Tamaño del arreglo: {a.size}")

Dimensiones del arreglo: 3
Forma del arreglo: (4, 2, 3)
Tamaño del arreglo: 24


In [21]:
b = np.ones(7, dtype=np.int8)
print(b)

[1 1 1 1 1 1 1]


In [22]:
b.dtype

dtype('int8')

In [23]:
c = np.full((3, 3), 7)
print(c)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


# CREACION DE ARREGLOS CON `arange()` + EL METODO `reshape()`

La funcion arange permite generar un arreglo de 1D con valores enteros en un rango especifico:

In [26]:
# np.arange(0,10,1)
arreglo_1 = np.arange(2,20,2)
print(arreglo_1)

[ 2  4  6  8 10 12 14 16 18]


In [30]:
arreglo_2 = np.arange(2, 15, dtype=np.int8)
print(arreglo_2)

[ 2  3  4  5  6  7  8  9 10 11 12 13 14]


In [ ]:
help(np.arange)

In [31]:
arreglo_3 = np.arange(3, 31, 3)
print(arreglo_3)

[ 3  6  9 12 15 18 21 24 27 30]


Y podemos usar la funcion reshape para convertir el vector a un arreglo de 2 o mas dimensiones

In [34]:
arreglo_4 = np.arange(2, 101, 2)
print(arreglo_4)
print("\nNro elementos", arreglo_4.size)

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]

Nro elementos 50


In [40]:
arreglo_5 = arreglo_4.reshape(5, 10)
print(arreglo_5)

[[  2   4   6   8  10  12  14  16  18  20]
 [ 22  24  26  28  30  32  34  36  38  40]
 [ 42  44  46  48  50  52  54  56  58  60]
 [ 62  64  66  68  70  72  74  76  78  80]
 [ 82  84  86  88  90  92  94  96  98 100]]


In [42]:
arreglo_4.reshape(25, 2)

array([[  2,   4],
       [  6,   8],
       [ 10,  12],
       [ 14,  16],
       [ 18,  20],
       [ 22,  24],
       [ 26,  28],
       [ 30,  32],
       [ 34,  36],
       [ 38,  40],
       [ 42,  44],
       [ 46,  48],
       [ 50,  52],
       [ 54,  56],
       [ 58,  60],
       [ 62,  64],
       [ 66,  68],
       [ 70,  72],
       [ 74,  76],
       [ 78,  80],
       [ 82,  84],
       [ 86,  88],
       [ 90,  92],
       [ 94,  96],
       [ 98, 100]])

# CREACION DE ARREGLOS CON `linspace()` + EL METODO `reshape()`

La funcion `linspace()` permitir generar un arreglo de 1D con valores decimales en un rango especifico

In [43]:
arreglo_6 = np.linspace(0, 10, 100)
print(arreglo_6)

[ 0.          0.1010101   0.2020202   0.3030303   0.4040404   0.50505051
  0.60606061  0.70707071  0.80808081  0.90909091  1.01010101  1.11111111
  1.21212121  1.31313131  1.41414141  1.51515152  1.61616162  1.71717172
  1.81818182  1.91919192  2.02020202  2.12121212  2.22222222  2.32323232
  2.42424242  2.52525253  2.62626263  2.72727273  2.82828283  2.92929293
  3.03030303  3.13131313  3.23232323  3.33333333  3.43434343  3.53535354
  3.63636364  3.73737374  3.83838384  3.93939394  4.04040404  4.14141414
  4.24242424  4.34343434  4.44444444  4.54545455  4.64646465  4.74747475
  4.84848485  4.94949495  5.05050505  5.15151515  5.25252525  5.35353535
  5.45454545  5.55555556  5.65656566  5.75757576  5.85858586  5.95959596
  6.06060606  6.16161616  6.26262626  6.36363636  6.46464646  6.56565657
  6.66666667  6.76767677  6.86868687  6.96969697  7.07070707  7.17171717
  7.27272727  7.37373737  7.47474747  7.57575758  7.67676768  7.77777778
  7.87878788  7.97979798  8.08080808  8.18181818  8

In [44]:
arreglo_7 = np.linspace(0, 10, 20)
print(arreglo_7)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [45]:
arreglo_8 = arreglo_7.reshape(4, 5)
print(arreglo_8)

[[ 0.          0.52631579  1.05263158  1.57894737  2.10526316]
 [ 2.63157895  3.15789474  3.68421053  4.21052632  4.73684211]
 [ 5.26315789  5.78947368  6.31578947  6.84210526  7.36842105]
 [ 7.89473684  8.42105263  8.94736842  9.47368421 10.        ]]


In [46]:
arr = np.linspace(0, 10, 100).reshape(20, 5)
print(arr)

[[ 0.          0.1010101   0.2020202   0.3030303   0.4040404 ]
 [ 0.50505051  0.60606061  0.70707071  0.80808081  0.90909091]
 [ 1.01010101  1.11111111  1.21212121  1.31313131  1.41414141]
 [ 1.51515152  1.61616162  1.71717172  1.81818182  1.91919192]
 [ 2.02020202  2.12121212  2.22222222  2.32323232  2.42424242]
 [ 2.52525253  2.62626263  2.72727273  2.82828283  2.92929293]
 [ 3.03030303  3.13131313  3.23232323  3.33333333  3.43434343]
 [ 3.53535354  3.63636364  3.73737374  3.83838384  3.93939394]
 [ 4.04040404  4.14141414  4.24242424  4.34343434  4.44444444]
 [ 4.54545455  4.64646465  4.74747475  4.84848485  4.94949495]
 [ 5.05050505  5.15151515  5.25252525  5.35353535  5.45454545]
 [ 5.55555556  5.65656566  5.75757576  5.85858586  5.95959596]
 [ 6.06060606  6.16161616  6.26262626  6.36363636  6.46464646]
 [ 6.56565657  6.66666667  6.76767677  6.86868687  6.96969697]
 [ 7.07070707  7.17171717  7.27272727  7.37373737  7.47474747]
 [ 7.57575758  7.67676768  7.77777778  7.87878788  7.97