## OPERADORES DE ARREGLOS

Los operadores en Numpy permiten realizar operaciones secillas sobre cada uno de los elementos de un arreglo

### OPERADORES ARITMETICAS CON ESCALARES

Podemos operar los operadores simples en Python (con `+`, `-`, `*`, `**`) para realizar operaciones aritmeticas entre un arreglo y un escalar

In [2]:
import numpy as np

arreglo = np.arange(5, 15)
print(arreglo)

[ 5  6  7  8  9 10 11 12 13 14]


In [3]:
arreglo + 2

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [4]:
arreglo - 2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [6]:
print(arreglo)
arreglo += 2
print(arreglo)

[ 5  6  7  8  9 10 11 12 13 14]
[ 7  8  9 10 11 12 13 14 15 16]


In [7]:
arreglo * 0.5

array([3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. , 7.5, 8. ])

In [8]:
arreglo ** 2

array([ 49,  64,  81, 100, 121, 144, 169, 196, 225, 256])

### OPERACIONES ARITMETICAS ENTRE ARREGLOS

Para realizar operacones de este tipo ambos arreglos deben tener el mismo tamaño:

In [9]:
arreglo_1 = np.linspace(3,5,10)
arreglo_2 = np.linspace(7,9,10)
arreglo_3 = np.linspace(10,15,12)
print(arreglo_1)
print(arreglo_2)
print(arreglo_3)

[3.         3.22222222 3.44444444 3.66666667 3.88888889 4.11111111
 4.33333333 4.55555556 4.77777778 5.        ]
[7.         7.22222222 7.44444444 7.66666667 7.88888889 8.11111111
 8.33333333 8.55555556 8.77777778 9.        ]
[10.         10.45454545 10.90909091 11.36363636 11.81818182 12.27272727
 12.72727273 13.18181818 13.63636364 14.09090909 14.54545455 15.        ]


In [10]:
arreglo_1 + arreglo_2

array([10.        , 10.44444444, 10.88888889, 11.33333333, 11.77777778,
       12.22222222, 12.66666667, 13.11111111, 13.55555556, 14.        ])

In [11]:
arreglo_1 * arreglo_2

array([21.        , 23.27160494, 25.64197531, 28.11111111, 30.67901235,
       33.34567901, 36.11111111, 38.97530864, 41.9382716 , 45.        ])

In [12]:
arreglo_1 * arreglo_3

ValueError: operands could not be broadcast together with shapes (10,) (12,) 

In [13]:
# 
matriz_1 = arreglo_1.reshape(5,2)
matriz_2 = arreglo_2.reshape(5,2)
print(matriz_1)
print(matriz_2)

[[3.         3.22222222]
 [3.44444444 3.66666667]
 [3.88888889 4.11111111]
 [4.33333333 4.55555556]
 [4.77777778 5.        ]]
[[7.         7.22222222]
 [7.44444444 7.66666667]
 [7.88888889 8.11111111]
 [8.33333333 8.55555556]
 [8.77777778 9.        ]]


In [15]:
matriz_multip = matriz_1 * matriz_2
print(f"Tamaño de la matriz resultante: {matriz_multip.size}")
print(f"Estructura de la matriz resultante: {matriz_multip.shape}")
print(matriz_multip)

Tamaño de la matriz resultante: 10
Estructura de la matriz resultante: (5, 2)
[[21.         23.27160494]
 [25.64197531 28.11111111]
 [30.67901235 33.34567901]
 [36.11111111 38.97530864]
 [41.9382716  45.        ]]


### OPERACONES LOGICAS

Se puede aplicar operadores de comparacion para comparar cada elemento del arreglo con un escalar o elemento a elemento (en el caso de comparar dos arreglos)

In [26]:
arr_1 = np.linspace(5,50,20)
print(arr_1)

[ 5.          7.36842105  9.73684211 12.10526316 14.47368421 16.84210526
 19.21052632 21.57894737 23.94736842 26.31578947 28.68421053 31.05263158
 33.42105263 35.78947368 38.15789474 40.52631579 42.89473684 45.26315789
 47.63157895 50.        ]


In [27]:
print(arr_1 >= 25)

[False False False False False False False False False  True  True  True
  True  True  True  True  True  True  True  True]


In [28]:
arr_2 = np.linspace(4,60,20)
print(arr_2)

[ 4.          6.94736842  9.89473684 12.84210526 15.78947368 18.73684211
 21.68421053 24.63157895 27.57894737 30.52631579 33.47368421 36.42105263
 39.36842105 42.31578947 45.26315789 48.21052632 51.15789474 54.10526316
 57.05263158 60.        ]


In [29]:
arr_2 > arr_1

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [30]:
arr_2 != arr_1

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])