## METODOS DE UN ARREGLO

Un arreglo de Numpy es un objeto tipo `ndarray` en Python. Y por ser un objeto tiene asociado unos metodos que permite ejecutar diferentes operaciones sobre el arreglo.

In [1]:
import numpy as np

vector = np.arange(5, 20)
matriz = np.linspace(1, 10, 20).reshape(5,4)

print("Vector:\n", vector)
print("Matriz:\n", matriz)

Vector:
 [ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Matriz:
 [[ 1.          1.47368421  1.94736842  2.42105263]
 [ 2.89473684  3.36842105  3.84210526  4.31578947]
 [ 4.78947368  5.26315789  5.73684211  6.21052632]
 [ 6.68421053  7.15789474  7.63157895  8.10526316]
 [ 8.57894737  9.05263158  9.52631579 10.        ]]


#### METODOS `max()`, `min()`, `argmax()`, `argmin()`

In [2]:
vector_maximo = vector.max()
vector_minimo = vector.min()
print(f"Vector: {vector}")
print(f"Valor maximo del vector: {vector_maximo}")
print(f"Valor minimo del vector: {vector_minimo}")

Vector: [ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Valor maximo del vector: 19
Valor minimo del vector: 5


In [3]:
matriz_maximo = matriz.max()
matriz_minimo = matriz.min()
print(f"matriz: {matriz}")
print(f"Valor maximo del matriz: {matriz_maximo}")
print(f"Valor minimo del matriz: {matriz_minimo}")

matriz: [[ 1.          1.47368421  1.94736842  2.42105263]
 [ 2.89473684  3.36842105  3.84210526  4.31578947]
 [ 4.78947368  5.26315789  5.73684211  6.21052632]
 [ 6.68421053  7.15789474  7.63157895  8.10526316]
 [ 8.57894737  9.05263158  9.52631579 10.        ]]
Valor maximo del matriz: 10.0
Valor minimo del matriz: 1.0


In [4]:
# maximos y minimos por filas (axis=1)
matriz_max_fila = matriz.max(axis=1)
matriz_min_fila = matriz.min(axis=1)
print(f"matriz:\n {matriz}")
print(f"Valor maximo de cada fila: {matriz_max_fila}")
print(f"Valor minimo de cada fila: {matriz_min_fila}")

matriz:
 [[ 1.          1.47368421  1.94736842  2.42105263]
 [ 2.89473684  3.36842105  3.84210526  4.31578947]
 [ 4.78947368  5.26315789  5.73684211  6.21052632]
 [ 6.68421053  7.15789474  7.63157895  8.10526316]
 [ 8.57894737  9.05263158  9.52631579 10.        ]]
Valor maximo de cada fila: [ 2.42105263  4.31578947  6.21052632  8.10526316 10.        ]
Valor minimo de cada fila: [1.         2.89473684 4.78947368 6.68421053 8.57894737]


In [ ]:
# maximos y minimos por columnas (axis=0)
matriz_max_col = matriz.max(axis=0)
matriz_min_col = matriz.min(axis=0)
print(f"matriz:\n {matriz}")
print(f"Valor maximo de cada columna: {matriz_max_col}")
print(f"Valor minimo de cada columna: {matriz_min_col}")

matriz:
 [[ 1.          1.47368421  1.94736842  2.42105263]
 [ 2.89473684  3.36842105  3.84210526  4.31578947]
 [ 4.78947368  5.26315789  5.73684211  6.21052632]
 [ 6.68421053  7.15789474  7.63157895  8.10526316]
 [ 8.57894737  9.05263158  9.52631579 10.        ]]
Valor maximo de cada columna: [ 8.57894737  9.05263158  9.52631579 10.        ]
Valor minimo de cada columna: [1.         1.47368421 1.94736842 2.42105263]


In [8]:
m_pos_max = matriz.argmax() # indice del maximo valor
m_pos_min = matriz.argmin() # indice del minimo valor
m_pos_max_fila = matriz.argmax(axis=1) # indice del maximo valor por fila
m_pos_max_col = matriz.argmax(axis=0) # indice del maximo valor por columna

print(f"matriz:\n {matriz}")
print(f"Valor maximo global de la matriz: {matriz_maximo}, ubicado en la posicion {m_pos_max}")
print(f"Valor minimo global de la matriz: {matriz_minimo}, ubicado en la posicion {m_pos_min}")
print(f"Posicion de los maximos en cada fila: {m_pos_max_fila}")
print(f"Posicion de los minimos en cada columna: {m_pos_max_col}")

matriz:
 [[ 1.          1.47368421  1.94736842  2.42105263]
 [ 2.89473684  3.36842105  3.84210526  4.31578947]
 [ 4.78947368  5.26315789  5.73684211  6.21052632]
 [ 6.68421053  7.15789474  7.63157895  8.10526316]
 [ 8.57894737  9.05263158  9.52631579 10.        ]]
Valor maximo global de la matriz: 10.0, ubicado en la posicion 19
Valor minimo global de la matriz: 1.0, ubicado en la posicion 0
Posicion de los maximos en cada fila: [3 3 3 3 3]
Posicion de los minimos en cada columna: [4 4 4 4]


### METODOS `mean()`, `std()`, `sum()`

Permiten calcular el promedio, la desviacion estandar, y la suma de los elementos del arreglo.

In [10]:
print(vector)
print(matriz)

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 1.          1.47368421  1.94736842  2.42105263]
 [ 2.89473684  3.36842105  3.84210526  4.31578947]
 [ 4.78947368  5.26315789  5.73684211  6.21052632]
 [ 6.68421053  7.15789474  7.63157895  8.10526316]
 [ 8.57894737  9.05263158  9.52631579 10.        ]]


In [12]:
# suma de los elementos del vector y la matriz
print(f"Suma de todos los elementos del vector: {vector.sum()}")
print(f"Suma de todos los elementos de la matriz: {matriz.sum()}")

Suma de todos los elementos del vector: 180
Suma de todos los elementos de la matriz: 110.0


In [14]:
print(f"Promedio por columna de la matriz: {matriz.mean(axis=0)}")
print(f"Promedio por fila de la matriz: {matriz.mean(axis=1)}")

Promedio por columna de la matriz: [4.78947368 5.26315789 5.73684211 6.21052632]
Promedio por fila de la matriz: [1.71052632 3.60526316 5.5        7.39473684 9.28947368]


In [15]:
print(f"Desviacion estandar de la matriz: {matriz.std()}")
print(f"Desviacion estandar por columna de la matriz: {matriz.std(axis=0)}")
print(f"Desviacion estandar por fila de la matriz: {matriz.std(axis=1)}")

Desviacion estandar de la matriz: 2.7313964040009777
Desviacion estandar por columna de la matriz: [2.67956254 2.67956254 2.67956254 2.67956254]
Desviacion estandar por fila de la matriz: [0.52959505 0.52959505 0.52959505 0.52959505 0.52959505]
