## FUNCIONES UNIVERSALES

#### FUNCIONES MATEMATICAS

Permiten aplicar funciones matematicas sobre cada elemento de un arreglo. Las principales son: `add`, `subtract`, `multiply`, `divide`, `remainder`, `exp`, `log`, `sqrt`, `power`, `abs` son las mas usandas

In [2]:
import numpy as np

A = np.random.randn(5,4) # matriz 5x4
B = np.random.randn(5,4)
print(A)
print()
print(B)

[[ 0.25491358  0.96044932 -1.20226592 -2.28878611]
 [-0.79508781  0.39765749  0.52622259 -0.22796989]
 [ 0.08969889  0.06199323 -0.66284784  0.46182374]
 [-0.29022905  0.30522352  2.05242475  0.17076773]
 [-0.47529673 -0.43479674 -0.73521016  0.30117168]]

[[ 0.19585916  0.39448331 -0.15705437 -0.3967849 ]
 [ 0.12263224  0.98834417 -0.3696324   0.59529759]
 [-1.1474574  -1.37420692  0.74530175  0.19615871]
 [ 0.4821222  -1.80226675  1.41586499 -0.59323386]
 [ 0.68278923 -0.3470694   0.89621855  1.00506741]]


In [3]:
C = np.multiply(A, B) # multiplicacion elemento a elemento
print(C)

[[ 0.04992716  0.37888123  0.18882112  0.90815576]
 [-0.0975034   0.39302246 -0.19450892 -0.13570992]
 [-0.10292566 -0.08519153 -0.49402165  0.09059075]
 [-0.13992587 -0.5500942   2.90595636 -0.1013052 ]
 [-0.32452749  0.15090464 -0.65890898  0.30269784]]


In [4]:
D = np.power(A, 2) # eleeva al cuadrado cada elemento de la matriz A
print(D)

[[6.49809340e-02 9.22462901e-01 1.44544335e+00 5.23854184e+00]
 [6.32164624e-01 1.58131480e-01 2.76910218e-01 5.19702693e-02]
 [8.04589141e-03 3.84316100e-03 4.39367256e-01 2.13281166e-01]
 [8.42329024e-02 9.31613958e-02 4.21244736e+00 2.91616187e-02]
 [2.25906984e-01 1.89048207e-01 5.40533980e-01 9.07043820e-02]]


#### FUNCION DEL ALGEBRA LINEAL

- producto punto (`dot`)
- producto de matrices (`matmul`)
- valores propios de una matriz (`eig`)
- norma de una matriz (`norm`)
- inversa de una matriz (`inv`)

In [5]:
matriz1 = np.random.randn(3, 4) # matriz 3x4
matriz2 = np.random.randn(4, 5) # matriz 4 x 5
matriz3 = np.matmul(matriz1, matriz2) # producto matricial 3 x 5

print(f"Matriz 1 de tamaño: {matriz1.shape}")
print(f"Matriz 2 de tamaño: {matriz2.shape}")
print(f"Matriz Resultante:\n {matriz3}")
print(f"de tamaño: {matriz3.shape}")

Matriz 1 de tamaño: (3, 4)
Matriz 2 de tamaño: (4, 5)
Matriz Resultante:
 [[ 0.35124011 -0.9980461   1.67703334  1.54129772 -0.1473216 ]
 [-1.3843629   0.87291025 -1.07759498 -0.12697703 -0.36786047]
 [ 2.06108182  1.54424193 -1.9818346  -0.07723443 -0.6569964 ]]
de tamaño: (3, 5)


#### FUNCIONES TRIGONOTRICAS

- seno (`sin`)
- coseno (`cos`)
- tangente (`tan`)

In [7]:
# calcular el coseno de cada elemento de una matriz
E = np.random.randn(10, 4)
print(E)
print()
coseno = np.cos(E)
print(coseno)
print(coseno.shape)

[[ 0.48644202 -1.03550755  1.40182686  0.05480898]
 [-0.28551683  0.07136305 -0.09112363 -1.73451365]
 [-0.08608946  0.24257948  0.02081266  0.31835365]
 [ 1.46192843  0.24862721 -1.31689634  0.24483276]
 [ 1.05088831  1.320934   -0.93336683 -0.08174238]
 [-0.2090134  -0.56474203  1.53420439 -0.56646585]
 [-0.62338051  0.60587237  0.08146749  1.70683583]
 [ 0.08642456  0.99016994  2.5655177   0.44900867]
 [-1.72213846 -0.27710372 -0.93882094  0.67310424]
 [ 1.40237729  0.17055197 -0.59923487  0.64403926]]

[[ 0.88400175  0.51008944  0.16816659  0.99849836]
 [ 0.95951621  0.99745474  0.99585111 -0.16298694]
 [ 0.99629659  0.97072159  0.99978342  0.94975202]
 [ 0.10865297  0.96925114  0.25118081  0.97017788]
 [ 0.49680031  0.24727056  0.59513168  0.99666095]
 [ 0.97823611  0.84472669  0.03658377  0.84380285]
 [ 0.81190962  0.82200562  0.99668336 -0.13562029]
 [ 0.99626772  0.54854778 -0.83860722  0.90087785]
 [-0.15076506  0.96185181  0.59073978  0.7818902 ]
 [ 0.16762396  0.98549123  0.