## COPIAS SHALLOW Y DEEP

#### Copias Shallow

In [1]:
import numpy as np

arr = np.array([5, 27, 82, 3, 14, 5])
print(arr)

[ 5 27 82  3 14  5]


In [2]:
# al hacer slicing del arreglo anterior y almacenarlo en un nuevo arreglo
slc = arr[3:]
print(slc)

[ 3 14  5]


In [4]:
# al modificar el contenido del slice (slc) que acabamos de crear
slc[1] = -10
print(slc)

[  3 -10   5]


In [5]:
# veamos el contenido del arreglo original
print(arr)

[  5  27  82   3 -10   5]


#### Copias Deep

In [7]:
slc2 = arr[3:].copy()
print(slc)

[  3 -10   5]


In [9]:
slc2[2] = 999
print(slc2)

[  3 -10 999]


In [10]:
print(arr)

[  5  27  82   3 -10   5]
